# - Postgres + PostgREST.
# - JWT secret is hardcoded here and also set inside DB by 06_login_rpc.sql.
# - Guest can read products. Authenticated users/admins get RLS-scoped CRUD.

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d appdb || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 20

  postgrest:
    image: postgrest/postgrest:latest
    depends_on:
      db: { condition: service_healthy }
    ports: ["3000:3000"]
    environment:
      PGRST_DB_URI: postgres://app:secret@db:5432/appdb
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ROLE_CLAIM_KEY: .role
      PGRST_JWT_SECRET: superlong-32byte-min-secret-change-me

volumes:
  dbdata:
