services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
    volumes:
      - ./:/docker-entrypoint-initdb.d:ro
      - ../pgdata:/var/lib/postgresql/data
